export const projectsData = [
  {
    id: 1,
    imageLink: "/images/payment-project.png",
    deployUrl: "https://payment-system-project-app.herokuapp.com/m",
    appName: "payment-system",
    description:
      "This is a Full Stack Application by using React, Node.js, Express & MongoDB Atlas. It is a simple project to mimic a 'Funds Transfer' like Venmo. You can query login, sign up, log out, search recipients, and transfer money through this app. Using JWT(JSON Web Tokens) for authentication and authorization.",
    techStacks: [
      "JavaScript",
      "React",
      "React Router",
      "Express",
      "Redux",
      "MongoDB Atlas",
      "Styled Component",
      "Node.js",
      "JWT",
    ],
    github: "https://github.com/fanhuanliang/Payment-System",
    youTubeLink: "https://www.youtube.com/watch?v=g4Gut7ZElOE",
  },
  {
    id: 2,
    imageLink: "/images/movie-search-project.png",
    deployUrl: "",
    appName: "Movie Search App",
    description:
      "Movie Search Application is a responsive React App using api from OMDb API. Users can search any movie and display the search results. Also, users can register an account or login for storing the favorite movie list.",
    techStacks: [
      "TypeScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
      "Redux",
      "Styled Component",
    ],
    github: "https://github.com/fanhuanliang/movie-search-app",
    youTubeLink: "https://www.youtube.com/watch?v=BiPkyorwQ24",
  },
  {
    id: 3,
    imageLink: "/images/lego-project.png",
    deployUrl: "",
    appName: "LEGO-Main-Product-Review",
    description:
      "My first fullstack application with small team. I am responsible for the review component.",
    techStacks: ["JavaScript", "React", "Node.js", "Express", "sass", "mysql"],
    github: "https://github.com/fanhuanliang/Main-Product-Review",
    youTubeLink: "https://www.youtube.com/watch?v=OM_BobTBpiw",
  },
  {
    id: 4,
    imageLink: "/images/calculator.png",
    deployUrl: "",
    appName: "mini-app-calculator",
    description: "Building a mini-app-calculator for fun.",
    techStacks: ["React", "TypeScript"],
    github: "https://github.com/fanhuanliang/mini-app-calculator",
    youTubeLink: "",
  },
];
